#    ___        _____    ___   ___ ___ ___ 
#   | __|_ ____|_   _|__| _ \ | _ ) _ )_  )
#   | _|\ \ / _ \| |/ -_)   / | _ \ _ \/ / 
#   |___/_\_\___/|_|\___|_|_\ |___/___/___|
#                                        
--- name:exoter_bb2
# parameter for distortion using the frame_helper
calibration_parameters:
  camLeft:
    fx: 837.98636
    fy: 838.56569
    cx: 509.74846
    cy: 376.99711
    d0: -0.35914
    d1: 0.16317
    d2: 0.00039
    d3: 0.00041
    width: 1024
    height: 768
  camRight:
    fx: 837.40801
    fy: 838.06473
    cx: 536.53701
    cy: 377.66591
    d0: -0.35499
    d1: 0.15218
    d2: 0.00019
    d3: -0.00016
    width: 1024
    height: 768
#Distance between left and right camera
  extrinsic:
    tx: 0.12042814 #baseline in x (meters)
    ty: 0.00063857 #baseline in y (meters)
    tz: 0.0003051 #baseline in z (meters)
    rx: 0.00125 #rotation along x (rad)
    ry: -0.00333 #rotation along y (rad)
    rz: 0.00542 #rotation along z (rad)

# bit depth per channel
output_format: :MODE_RGB
undistort: false

--- name:loc_cam_front
# parameter for distortion using the frame_helper
calibration_parameters:
  camLeft:
    fx: 837.98636
    fy: 838.56569
    cx: 509.74846
    cy: 376.99711
    d0: -0.35914
    d1: 0.16317
    d2: 0.00039
    d3: 0.00041
    width: 1024
    height: 768
  camRight:
    fx: 837.40801
    fy: 838.06473
    cx: 536.53701
    cy: 377.66591
    d0: -0.35499
    d1: 0.15218
    d2: 0.00019
    d3: -0.00016
    width: 1024
    height: 768
#Distance between left and right camera
  extrinsic:
    tx: 0.12042814 #baseline in x (meters)
    ty: 0.00063857 #baseline in y (meters)
    tz: 0.0003051 #baseline in z (meters)
    rx: 0.00125 #rotation along x (rad)
    ry: -0.00333 #rotation along y (rad)
    rz: 0.00542 #rotation along z (rad)

# bit depth per channel
output_format: :MODE_RGB
undistort: false

#    _  _ ___  ___ ___   ___ ___ ___ 
#   | || |   \| _ \ _ \ | _ ) _ )_  )
#   | __ | |) |  _/   / | _ \ _ \/ / 
#   |_||_|___/|_| |_|_\ |___/___/___|
#                                    
--- name:hdpr_bb2
calibration_parameters:
  camLeft:
    fx: 846.05099
    fy: 848.13761
    cx: 528.68513
    cy: 403.67772
    d0: -0.32760
    d1: 0.11873
    d2: 0.00027
    d3: 0.00034
    width: 1024
    height: 768
  camRight:
    fx: 848.07570
    fy: 848.48201
    cx: 509.17747
    cy: 400.73848
    d0: -0.33204
    d1: 0.13558
    d2: 0.00096
    d3: 0.00135
    width: 1024
    height: 768
#Distance between left and right camera
  extrinsic:
    tx: -0.11864490 #baseline in x (meters)
    ty: -0.00017054 #baseline in y (meters)
    tz: -0.01169914 #baseline in z (meters)
    rx: 0.00336 #rotation along x (rad)
    ry: 0.00187 #rotation along y (rad)
    rz: -0.00300 #rotation along z (rad)

# bit depth per channel
output_format: :MODE_RGB
undistort: false

#--- name:stitch
# Distance in pixels between left and right image for a rough stitching. Leave empty for not stitching

#    ___           ___            
#   | _ \__ _ _ _ / __|__ _ _ __  
#   |  _/ _` | ' \ (__/ _` | '  \ 
#   |_| \__,_|_||_\___\__,_|_|_|_|
#                                 
--- name:pan_cam_left
calibration_parameters:

  camLeft:
    fx: 1419.51493    
    fy: 1425.72107
    cx: 634.86337   
    cy: 488.17301
    d0: -0.25241
    d1: 0.19399
    d2: -0.00076
    d3: -0.00116
    width: 1280
    height: 960
  camRight:
    fx: 1420.96363   
    fy: 1428.58319
    cx: 649.16979   
    cy: 495.44686
    d0: -0.25239                
    d1: 0.21476
    d2: -0.00133
    d3: -0.00086
    width: 1280
    height: 960
  extrinsic:
    tx: -0.25339977     
    ty: -0.00113082 
    tz: 0.00282068
    rx: -0.00364     
    ry: -0.00017  
    rz: 0.00048

# bit depth per channel
output_format: :MODE_RGB
undistort: false

--- name:pan_cam_right
calibration_parameters:

  camLeft:
    fx: 1419.51493    
    fy: 1425.72107
    cx: 634.86337   
    cy: 488.17301
    d0: -0.25241
    d1: 0.19399
    d2: -0.00076
    d3: -0.00116
    width: 1280
    height: 960
  camRight:
    fx: 1420.96363   
    fy: 1428.58319
    cx: 649.16979   
    cy: 495.44686
    d0: -0.25239                
    d1: 0.21476
    d2: -0.00133
    d3: -0.00086
    width: 1280
    height: 960
  extrinsic:
    tx: -0.25339977     
    ty: -0.00113082 
    tz: 0.00282068
    rx: -0.00364     
    ry: -0.00017  
    rz: 0.00048

# bit depth per channel
output_format: :MODE_RGB
undistort: false


