--- name:default
# Path to the joystick device
device: /dev/input/js0
# Maximum rotation speed in rad/s
maxRotationSpeed: 0.18539815 #3.141592653589793
# Minimum rotation speed in rad/s
minRotationSpeed: 0.18539815 #-3.141592653589793

# Maximum translation speed in m/s
maxSpeed: 0.1
# Minimum translation speed in m/s
minSpeed: -0.1
# no documentation available for this property
#metadata:
#  metadata: []
#  properties: []
#  input_ports: []
#  output_ports: []

--- name:thrustmaster
# no documentation available for this property
axisScale: [1.0, 1.0, 1.0, -1.0, 1.0, 1.0]

--- name:logitech_attack3
# no documentation available for this property
axisScale: [1.0, 1.0, -1.0]

--- name:predator_trust
# no documentation available for this property
axisScale: [1.0, 1.0, 0.0, -1.0, 1.0, -1.0, -1.0]

--- name:logitech_gamepad
# no documentation available for this property
axisScale: [1.0, 1.0, -1.0, -1.0, 1.0, 1.0]


