--- name:exoter
# the device port
serial_port: /dev/ttyS4  #ttyS4 for PC104, if connected through USB/Serial converter then use ttyUSB1
# Baud rate to open the serial com_port.
serial_baudrate: 38400
# the expected time (in seconds) to have a whole package in the fd (the device port)
serial_timeout: 0.2
# from frame for the transformer
gnss_source_frame: "body" #transformer names. No transformation convention
# to frame for the transformer
gnss_target_frame: "world_osg" #transformer names. No transformation convention

--- name:EvaluationBoard
# the device port
serial_port: /dev/ttyUSB0
# Baud rate to open the serial com_port.
serial_baudrate: 38400
# the expected time (in seconds) to have a whole package in the fd (the device port)
serial_timeout: 0.1

--- name:Netherlands
# This UTM zone is also valid for Toulouse (CNES)
# UTM zone for conversion of WGS84 to UTM
utm_zone: 31
# UTM north for conversion of WGS84 to UTM
utm_north: true
# Geodetic datum typically NAD83 or WGS84 
geodetic_datum: WGS84

--- name:ESTEC
# Origin in UTM coordinates, that is used for position readings.
pose_origin:
  data:
  - 597220.14273647161
  - 5786238.5623347349
  - 2.9529999999999998

--- name:SEROM
# Origin in UTM coordinates, that is used for position readings.
pose_origin:
  data:
  - 377771.4
  - 4823945.2
  - 143.674

--- name:DECOS
# Origin in UTM coordinates, that is used for position readings.
pose_origin:
  data:
  - 597400.9       # (597467.8-81.9)+14
  - 5785944.4      # (5785972.5-55.1)+24
    #- 597197.5       # (597467.8-81.9)
    #- 5786210.4      # (5785972.5-55.1)
  - 1.95


# no documentation available for this property
#metadata:
#  metadata: []
#  properties: []
#  input_ports: []
#  output_ports: []

